env:
  TERM: xterm-256color

window:
  opacity: 0.95
  dimensions:
    columns: 147
    lines: 45

  padding:
    x: 10
    y: 10

  decorations: none

font:
  size: 15.0

  normal:
    family: "Hack Nerd Font"
    style: Regular
  bold:
    family: "Hack Nerd Font"
    style: Bold
  italic:
    family: "Hack Nerd Font"
    style: Italic

colors:
  # Default colors
  primary:
    #background: '#1d1f21'
    background: '#000000'
    foreground: '#c5c8c6'

key_bindings:
  - { key: Left, mods: Alt, chars: "\x1bb" }
  - { key: Right, mods: Alt, chars: "\x1bf" }

  # Command / -> Comment
  - { key: Slash, mods: Command, chars: "gcc" }

  - { key: Key3, mods: Option, chars: "#" }

  # Rename the current tmux window
  - { key: Comma, mods: Command, chars: "\x02\x2c" }
  # Select a new tmux session for the attached client interactively
  - { key: Semicolon, mods: Command, chars: "\x02\x73" }
  # Switch to last tmux session
  - { key: L, mods: Command, chars: "\x02\x4c" }
  - { key: LBracket, mods: Command, chars: "\x02\x5b" }
  # Change to the previous tmux window
  - { key: LBracket, mods: Command|Shift, chars: "\x02\x70" }
  # Split the current pane into two, left and right
  - { key: N, mods: Command|Shift, chars: "\x02\x25" }
  # Split the current pane into two, top and bottom.
  - { key: N, mods: Command, chars: "\x02\x22" }
  # Detach the current tmux client
  # - { key: Q, mods: Command, chars: "\x02\x64" }
  # Change to the next tmux window
  - { key: RBracket, mods: Command|Shift, chars: "\x02\x6e" }
  # Type <escape>:w<enter> to save neovim
  - { key: S, mods: Command, chars: "\x1b\x3a\x77\x0a" }
  # Create a new tmux window
  - { key: T, mods: Command, chars: "\x02\x63" }
  # Break the current tmux pane out of the tmux window
  - { key: T, mods: Command|Shift, chars: "\x02\x21" }
  # Kill the current tmux pane (and window if last pane)
  # - { key: W, mods: Command, chars: "\x02\x78" }
  # Toggle the zoom state of the current tmux pane
  - { key: Z, mods: Command, chars: "\x02\x7a" }
